"""empty message

Revision ID: 2060e46a4f2b
Revises: d28cf4256b06
Create Date: 2020-03-14 13:27:21.681926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2060e46a4f2b'
down_revision = 'd28cf4256b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todolists SET completed = False WHERE completed is NULL;')

    op.alter_column('todolists', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
